window.PUBLICATIONS = [
  {
    "No": "",
    "Year": "2026",
    "Category": "AI & Computational Design",
    "Keywords": "AI, Neural Operator, Physics-guided Simulation, Electromagnetic Field Prediction, Nanophotonics",
    "Title": "Broadband Electromagnetic Field Prediction at Unseen Wavelengths via Physics-Guided Neural Operators",
    "Authors": "J. Seo†, C. Kang†, D. Seo, H. Chung*",
    "Journal": "Nanophotonics (Under review)",
    "Link": "https://arxiv.org/abs/2408.02971",
    "Image": "https://drive.google.com/thumbnail?id=1l5n8G9cc9Zths0I72hzBv1u8OdHRJMkg&sz=w800",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Neural Operator",
    "Note": ""
  },
  {
    "No": "",
    "Year": "2026",
    "Category": "Imaging & Display",
    "Keywords": "Color Router, Inverse Design, Angle Robustness, Image Sensor, Structural Similarity",
    "Title": "Inverse Design of Angle-Robust Color Routers by Optical Structural Similarity",
    "Authors": "Donghyun Kim, J. Han, S. Lee, M. Jang, H. Chung*",
    "Journal": "ACS Photonics (Under review)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1MLTUfcFiExZlRvH4TnVizR-BvzyeBW3G&sz=w1000",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Color Router / Inverse Design",
    "Note": ""
  },
  {
    "No": "",
    "Year": "2026",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "Metasurface, Optical Skyrmion, Topological Photonics, Inverse Design",
    "Title": "Inverse-Designed Metasurfaces for Compact Optical Skyrmion Generation with High Topological Fidelity",
    "Authors": "D. Park, A. Song, H. Chung*, S. Kim*",
    "Journal": "Advanced Optical Materials (Under review)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Metasurface / Optical Skyrmion",
    "Note": ""
  },
  {
    "No": "[52]",
    "Year": "2026",
    "Category": "Integrated Photonics & Quantum",
    "Keywords": "Thin-Film Lithium Niobate, Two-Photon Interference, On-Chip Photonics, Quantum Photonics",
    "Title": "Versatile On-Chip Reconfigurable Two-Photon Interference Platforms Using Thin-Film Lithium Niobate",
    "Authors": "Minho Choi‡, Changhyun Kim‡, Sunghyun Moon, Hyeon Hwang, Min-Kyo Seo, Hyang-Tag Lim, Haejun Chung, Hojoong Jung*, and Hyounghan Kwon*",
    "Journal": "APL Photonics (2026) (IF:5.3, JCR~20%)",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Integrated Photonics",
    "Note": "Front Cover selected"
  },
  {
    "No": "[51]",
    "Year": "2026",
    "Category": "AI & Computational Design",
    "Keywords": "AI, Ordinal Classification, Calibration, Dynamic Regularization, Unimodality",
    "Title": "MORCU: Margin-Based Ordinal Classification with Dynamic Regularization for Calibration and Unimodality",
    "Authors": "Daehwan Kim, H. Chung*, I. Jang*",
    "Journal": "Pattern Recognition (2026) (IF:7.6, JCR~9%)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=19cSbdE7ROjmMXTH-ciBxsYXyH-PFEo6h&sz=w800",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Ordinal Classification",
    "Note": "Editor's pick"
  },
  {
    "No": "[50]",
    "Year": "2026",
    "Category": "Biomedical AI",
    "Keywords": "AI, Medical Imaging, MRI, PET, Cross-modal Synthesis, Perceptual Loss",
    "Title": "Cyclic 2.5D Perceptual Loss for Cross-Modal 3D Image Synthesis: T1 MRI to Tau-PET",
    "Authors": "J. Moon, S. Kim, H. Chung*, I. Jang*",
    "Journal": "Human Brain Mapping (2026) (IF:3.5, JCR~17%)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1-5n1rexPlMSail7tVhJL5dW7A5p9KWJM&sz=w800",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Medical Imaging",
    "Note": ""
  },
  {
    "No": "[49]",
    "Year": "2026",
    "Category": "AI & Computational Design",
    "Keywords": "AI, Multi-View Fusion, Mutual Distillation, View Combination",
    "Title": "Hierarchical Mutual Distillation for Multi-View Fusion: Learning from All Possible View Combinations",
    "Authors": "J. Yang, H. Chung*, I. Jang*",
    "Journal": "Pattern Recognition (2026) (IF:7.6, JCR~9%)",
    "Link": "https://arxiv.org/abs/2411.10077",
    "Image": "https://drive.google.com/thumbnail?id=19wxxwVhCVu-G5KecztcErtbuUzhytYng&sz=w800",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Multi-View Fusion",
    "Note": ""
  },
  {
    "No": "[48]",
    "Year": "2026",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "Topology Optimization, Adjoint Method, Time-domain Simulation, Band-selective Design",
    "Title": "Multi-objective time-domain adjoint via temporal convolution for band-selective electromagnetic topology optimization",
    "Authors": "M. Park, S. Boriskina, H. Chung*",
    "Journal": "Result in Physics (2026) (IF:4.8, JCR~20%)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1pMl8aVVhB7LhHAemddj7ROJy7boh1gDe&sz=w800",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Topology Optimization",
    "Note": ""
  },
  {
    "No": "[47]",
    "Year": "2026",
    "Category": "AI & Computational Design",
    "Keywords": "AI, Ranking, Human-in-the-loop, VLM, Pairwise Comparison",
    "Title": "Dodgersort: Uncertainty-Aware VLM-Guided Human-in-the-Loop Pairwise Ranking",
    "Authors": "Y. Park, H. Chung*, I. Jang*",
    "Journal": "PAKDD (2026) (BK21 Conference, Oral Presentation)",
    "Link": "",
    "Image": "https://drive.google.com/thumbnail?id=1aiyO9MFxCZrlQBcGy5BE6ipuEI4ie0Mq&sz=w800",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Human-in-the-loop Ranking",
    "Note": ""
  },
  {
    "No": "[46]",
    "Year": "2026",
    "Category": "Nanophotonics & Inverse Design",
    "Keywords": "AI, Diffusion Model, Inverse Design, Fabrication-aware Design, Photonic Devices",
    "Title": "Physics-guided and fabrication-aware inverse design of photonic devices using diffusion models",
    "Authors": "Dongjin Seo†, Soobin Um†, Sangbin Lee, Jong Chul Ye* and Haejun Chung*",
    "Journal": "ACS Photonics (2026) (IF:6.7, JCR 14%)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUDrVjS1sIFRxTMbPbXC0a96WQdtcTeO2Ng6lBGHKJD68mDlnHfoxXuNjUaKVWpWJLSS4YxZvhqdY6UXkmOlf9waV25vNiXbKktf3LrE7TrH9VUdJeGD5vDfTAnpAHJ23Vg8Uwxw6nquG2pt6Mnr71eb5ozMx35R68DROIowDeQcCifnDuGBnXpDZNnsP3bJz5bdLIYR3tycQ7g0XrrlGESMZVEFZzs5uEc1%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Inverse Design / Diffusion Model",
    "Note": ""
  },
  {
    "No": "[45]",
    "Year": "2026",
    "Category": "Imaging & Display",
    "Keywords": "AI, Metalens Imaging, Image Translation, Image Synthesis",
    "Title": "Metalens-Style Image Synthesis for Metalens Imaging via Image-to-Image Translation",
    "Authors": "Chanik Kang†, Hyewon Suk†, Joonhyuk Seo, Ikbeom Jang* and Haejun Chung*",
    "Journal": "Scientific Report (2026) (IF:3.9, JCR~25%)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUD1TAQLQyEFSxnbEoJeHuH7p-VU65NvaepogeBdjN9cV0A7k1CsPPpxlkOgruTFzuTk2UvhlwP2lD330wkVqOxUKCJ1h8EncwWvJXoxeqY-Uxf0rONltWxg39XkshxohmhVyb-qZGuw-F8rZnSIiH_O_RNMifc7qq5Oq4YZJWaBV6V4tJt2DDYHQkHt57cPxxi1QAhlUo4725edQaxHlsOSOmAIIylcwGBBolE%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Metalens Imaging",
    "Note": ""
  },
  {
    "No": "[44]",
    "Year": "2026",
    "Category": "Imaging & Display",
    "Keywords": "Thermal Imaging, Metalens, Inverse Design, Microbolometer, Wide FOV",
    "Title": "Inverse Design of Thermal Imaging Metalens Achieving 100 degrees Field-of-View on a 4 × 4 Microbolometer Array",
    "Authors": "Munseong Bae†, Eunbi Jang†, Chanik Kang†, Haejun Chung*",
    "Journal": "Micromachines (2026) (IF:3.0)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUDr57DerVjZxdPf2JTLYotxE_lL8OFyizeyNTf8c_GhhvKs5CiCHfCPGlxPuQSx5D_wMkgW_EBTk4kO20CMWhzfdWtywl3OwhMXLqLU47mJFDh0h8WvkWDByNjPg050DzMRC-k0jwVE8CP8Fz6m4THzlN-oNKgk9_JoU8fzxZlaAZcrfN7fwH9mv3TxiBsD4fdug-snMYG2JvMEeLtGHV9S4TRgq9BAfUqO%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Thermal Metalens",
    "Note": ""
  },
  {
    "No": "[43]",
    "Year": "2026",
    "Category": "Imaging & Display",
    "Keywords": "Color Router, Nanophotonics, Inverse Design, Oblique Incidence, Image Sensor",
    "Title": "Inverse Design of Nanophotonic Color Router Robust to Oblique Incidence",
    "Authors": "Jaehyun Jeon, Chanhyung Park, Doyoung Heo, Haejun Chung, Min Seok Jang*",
    "Journal": "Advanced Optical Materials (2026) (IF:7.2)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUDxgCbTj-giTDAfJjFMHma_R_Uk-7YG29BtaV201p3S-vzEzXrIIZo-rw9DHrEkbL3Y9UUAVpfankwk2dzJnkdzHSwHXgDx-B-erOyE_DUTIZ32tE0U1lk2eEGE-Tq5ucf9eb63z49ky8tKksOnvLkI3aouJ5wQcKeFlOq1TrJt6VporkNSUy8EYHIY8ladE0n1Juj1QvZQYIfvoJWc6GAqY6Wl25qes5f0%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Color Router / Nanophotonics",
    "Note": ""
  },
  {
    "No": "[42]",
    "Year": "2026",
    "Category": "Biomedical AI",
    "Keywords": "AI, fMRI, Brain Network, Resting-State fMRI, Task fMRI",
    "Title": "BOLDSimNet: Examining Brain Network Similarity between Task and Resting-State fMRI",
    "Authors": "B. Kim, DD. Chakladar, H. Chung*, I. Jang*",
    "Journal": "Under review",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUBGLyXCpVif1k4-TXpjJntCVh6gzroNor0hDKj98r7L8kSFaHtsHcxSzpZ22zjHgHKK2FdfijEiWbZON7nqJ_oeu167GGclla9GrK4LueiFEZUuAzH3GfjnugnJDbck6hFuhx-41opJgG1En6_uKqa_6AsBbaT_zwUDuTmJC5YPQOZOpoREqwxhw83hVRPbxywR8i0wvc5kxg1bSO9ut0fKF8cyZ0u1qkKOs9U%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / fMRI",
    "Note": ""
  },
  {
    "No": "[41]",
    "Year": "2026",
    "Category": "AI & Computational Design",
    "Keywords": "AI, Ordinal Regression, Calibration, Neural Network",
    "Title": "Calibration of ordinal regression networks",
    "Authors": "D. Kim, H. Chung*, I. Jang*",
    "Journal": "Under review",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUCZN47WHS2EACol82H0d43v26OWTkLFrD06b7noXCcO66ZJjG7r3pQy5zAI06miQficGstw0Lea-LHzy7lUJs47njFE4b9svWkrmcIxki6qgHI5K3vUvVitOwzBnKUTNDQ3mQ6-nA8ek6eFPdIU2cIoI2Eg3sduGEC5qUkUoK3-MAFyuq7zv6krW55u92749yOgMamN0v7wq3674pbCddOJNl6gUkwH6bcI8zo%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Ordinal Regression",
    "Note": ""
  },
  {
    "No": "[40]",
    "Year": "2026",
    "Category": "AI & Computational Design",
    "Keywords": "AI, Ranking, Human-in-the-loop, Metalens Image Quality",
    "Title": "MetaRanker: Human-in-the-loop Active Ranking for Metalens Image Quality",
    "Authors": "Y. Park, H. Chung*, I. Jang*",
    "Journal": "Under review",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUCozPqDm3FMrJZAfu8LrXLJ72aWtxSbRW9EOLSwuLXX0H0zv2ZuV1UJ5-gvtbR_oS-bKa-owTpk5w7RCrjTZ5jeckNwkSq6bWRZp3JeIOfsjHXvVag3yXSMj-x_9AcRYCQ3Zyu70Cn4LXByq2An1SomnSbrqCoW5I8HwH_3kLdO416WIRTPwFmgZ8QjbSQyeYe323DpO1UXiOlyfEgeQHpmCQALBALI703N%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Ranking",
    "Note": ""
  },
  {
    "No": "[39]",
    "Year": "2026",
    "Category": "AI & Computational Design",
    "Keywords": "Neural Operator, Fourier Neural Operator, Adjoint Method, Meta-optics, Inverse Design",
    "Title": "Neural Adjoint Method for Meta-optics: Accelerating Volumetric Inverse Design via Fourier Neural Operators",
    "Authors": "C. Kang, H. Suk, H. Chung*",
    "Journal": "Under review",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUB3FyHuOR9eqXfe4cIOkTq9Rl4jsbahZ8979jQxIK9jIcw_-xyn85XvsCvW9gKMgPaBovPhHdTwVC9r_Cqt1yU2nMXJdujGteVfWToOWxZ1csHXTg9lZmGANGnGbS-P_1fjXRXHKagQh-ZJOaxI2AgDWEqk0XnCfdryAtFWOLA9bs8eC4x1j2ajX2F6S5lHPpxN7xMiHK8O7hvClFW7Hwc8qrpZN9xIH6IbwQY%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Neural Operator / Meta-optics",
    "Note": ""
  },
  {
    "No": "[38]",
    "Year": "2026",
    "Category": "Materials & Light-Matter Interaction",
    "Keywords": "2D Materials, WS2, Plasmonics, Nanocubes, Valley-polarized Emission",
    "Title": "Enhanced valley-polarized emission in n-doped WS2 via plasmonic nanocubes",
    "Authors": "Ha Young Lee, Munseong Bae, Alexander Corletto, Feier Fang, James Bullock, Haejun Chung, and Sejeong Kim*",
    "Journal": "Under review",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "2D Materials / Plasmonics",
    "Note": ""
  },
  {
    "No": "[37]",
    "Year": "2026",
    "Category": "Materials & Light-Matter Interaction",
    "Keywords": "2D Materials, Optical Vortex, van der Waals Materials, High Efficiency",
    "Title": "Near-unity efficiency optical vortex generation in van der Waals materials",
    "Authors": "Sujeong Byun, Munseong Bae, Hangsung Cho, Haejun Chung, Kostya Novoselov, James Bullock and Sejeong Kim*",
    "Journal": "Under review",
    "Link": "",
    "Image": "",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "2D Materials / Optical Vortex",
    "Note": ""
  },
  {
    "No": "[36]",
    "Year": "2025",
    "Category": "Imaging & Display",
    "Keywords": "AR, Waveguide Coupler, Inverse Design, Optical See-through Display",
    "Title": "Optical see-through augmented reality via inverse-designed waveguide couplers",
    "Authors": "Seunghyun Lee, Byounghyo Lee and Haejun Chung*",
    "Journal": "Nanophotonics (2025) (IF:7.5)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUDVY6_6i6veNP1A99ETLh77qkZR1zxiwxcVmxZIVpqw73IUHlG-EsQsYiCk0Jk3aLHVPREZbV43Xh3hyK38bi1ADxCarvIlkEeYsLrXw9H8ExZPliLQDWkfz1pkCYK4lazpNVJ6IwYtFTRNED7YaIwgL--PQGgsg3pUeqLHcdrqShcYN5-0DsAEgSE8Dvm15DRW1_4ehTTq8gW7jNf7r_TSKlO-Ss0g9O-_%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AR / Waveguide Coupler",
    "Note": ""
  },
  {
    "No": "[35]",
    "Year": "2025",
    "Category": "Materials & Light-Matter Interaction",
    "Keywords": "Chiral Nanophotonics, Chiroptical Response, Inverse Design",
    "Title": "Inverse design for enhanced chiroptical response with chiral nanophotonic structures",
    "Authors": "Munseong Bae†, Chia-Chun Pan†, Chanik Kang†, Jinseong Bae, Donghyun Park, Seokho Lee, Cherry Park, Haoran Ren, Junsuk Rho, Haejun Chung*, and Sejeong Kim*",
    "Journal": "APL Photonics (2025) (IF:5.3, JCR 18%)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUC9MSxGm7dyz6zj_7ynK4-Mo67kC_ycINFDb5L_W4PW5jUxn5RWTZvEuDkcQasNTgtKO1X69-yPVHEK1VrDeBZNcWQVQlSD875Kp4uggCuniOijIxVgA_vuBkGC9nvIOa_811wwMi9BJno5SIkKV4lKQgZ_u2JjRMyigj7L8aoQGcnr_Dghw-RHy_5Di96uhFYjsOwV9drR057r24xDOd1YD-o_6Roqv-vCL2Q%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Chiral Nanophotonics",
    "Note": ""
  },
  {
    "No": "[34]",
    "Year": "2025",
    "Category": "AI & Computational Design",
    "Keywords": "AI, Sorting, Human-in-the-loop, CLIP, Pairwise Comparison",
    "Title": "EZ-Sort: Efficient Pairwise Comparison via Zero-Shot CLIP-Based Pre-Ordering and Human-in-the-Loop Sorting",
    "Authors": "Y. Park, H. Chung*, I. Jang*",
    "Journal": "CIKM (2025) (BK21 Conference)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUDHthm5zuLjgj4lC8ag_fqI5JFTGliOeFgYZut4kdc4mRMxH74tARaCj8AYN0jqbk9XYEs_oR_bdzY4zYoaiZtbHFvKjYVuhk3omngLSU-377BAvKTkBvvmilYRB-qvcifEI7J0RGuuR8Q2sCTcB8bXJPQ-Wig-Zn6FQgcVhCGxPkScObaT2X-7QEQ398gFzLVdA0j0F98lqO9qhuVmdhMT8PmcX8msfA027Mc%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "AI / Sorting",
    "Note": ""
  },
  {
    "No": "[33]",
    "Year": "2025",
    "Category": "Materials & Light-Matter Interaction",
    "Keywords": "2D Materials, Optical Vortex, Spin-Orbit Coupling, van der Waals Materials",
    "Title": "Spin-Orbit Coupling for Optical Vortex Generation in van der Waals Materials",
    "Authors": "J. Jo†, S. Byun†, M. Bae, J. Wang, H. Chung*, S. Kim*",
    "Journal": "Light: Science & Applications (2025) (IF:23.4, JCR~2.9%)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUC4Ljp1FCe1yVFWSFgphnXuLmUR7W--7CEayWkfKq4j4ylvlqfdIj5TXQfVTpyRxB34r2apBvwO3mSaLA3cbYQkUd1QYCm5IRMfXPPrXwCzCaVEbPR_vVskvBOTUWICkDJs0emJddPDMdW0IhST0aZ9kNVprpyP4Mh8Q8BEDazCUB4u2ydNpGaTg4a-qzx8UZVghcSZAWuwu5XPqEhNglPiPelI4MLbJVZMyN0%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "2D Materials / Optical Vortex",
    "Note": ""
  },
  {
    "No": "[32]",
    "Year": "2025",
    "Category": "Imaging & Display",
    "Keywords": "UDC, Metasurface Imaging, Wavefront Restoration, Under-Display Camera",
    "Title": "Inverse-Designed Metasurfaces for Wavefront Restoration in Under-Display Camera Systems",
    "Authors": "J. Jo†, M. Lee†, S. Lee†, C. Kang, H. Chung*",
    "Journal": "Nanophotonics (2025) (IF:7.5)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUCUh_UTa3JqBAFD94FUwNsbGfnd2sf9xNpLV93Ll4vNs6ny9TVXiFIz43Y6xXL5rxrev1uwKJz046T9lWu7ZDVSArM3Gt6eKf5oGSUJJyFSClYCexICOg-XI90M1bXhGH5GDZV6Hs-TuskAQ6sLWqT24ZmAnqWYh4e-IrsQDe7o1fmlJ8WOWdr_TLaa7LT_NmQBPpIZMn85J56wltGIVzrHqCWknmpSRqr4ZYQ%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "UDC / Metasurface Imaging",
    "Note": ""
  },
  {
    "No": "[31]",
    "Year": "2025",
    "Category": "Energy & Thermal Photonics",
    "Keywords": "Metamaterial Absorber, Inverse Design, Ultrathin Absorber",
    "Title": "Inverse design of ultrathin metamaterial absorber",
    "Authors": "E. Jang†, J. Cho†, C. Kang*, H. Chung*",
    "Journal": "Nanomaterials (2025) (IF:4.3)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUA0ScXmMY_Po_lpB1IBJFFnzCjpuHg7ReQA6_N_Noag_GsqAlpJSTh_M_FUirmdz5GLPgqnjXu8EjB40lMKxlgLO2MTJdpHx-SELVsOgkIsUdDBYB94YM9PX3-xYSTqXQ4Ithe2yryS_TuzJ6PzqvxiFK3yASz0FLFx2ukR-MUZ9akax61L7X7r_wA4nNAbqNwQkmz4jrt-ObOJC9PE8gYjUNIPrdRCFtNW_X_o%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Metamaterial Absorber",
    "Note": ""
  },
  {
    "No": "[30]",
    "Year": "2025",
    "Category": "Energy & Thermal Photonics",
    "Keywords": "Radiative Cooling, Thermal Photonics, Manufacturing, Applications",
    "Title": "Design strategies, manufacturing, and applications of radiative cooling technologies",
    "Authors": "Joonho Kang†, Changkyun Lee†, Haejun Chung* and Peter Bermel*",
    "Journal": "Nanophotonics (2025) (IF:7.5)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUCqXTomRkges0WT36H-ANsQbD79UvbtyyQPnZCTIqAnngZbBDM1IebsYiMg2LxsDNNde_RgOfRcY3tutlLsiWRZWMM0jnOoGube8O1w782kOap809VfAyNMdmlngK5YdB6uTEjkQTmhuElmQqWJljI4p_x7_aOAk26sxxlZwa9pIjy5YovoKVXBD60FszsxufYwS27MNWjuug5xIJtIiSMJU2-d1do_XAUo4is%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Radiative Cooling",
    "Note": ""
  },
  {
    "No": "[29]",
    "Year": "2025",
    "Category": "Materials & Light-Matter Interaction",
    "Keywords": "Chiral Nanophotonics, Helical Dichroism, Inverse Design",
    "Title": "Inverse Design of Chiral Structures for Giant Helical Dichroism",
    "Authors": "C.-C. Pan†, M. Bae†, H. Wang, J. Lim, R. R. Unnithan, J. Yang, H. Chung*, S. Kim*",
    "Journal": "Nanoscale Horizons (2025) (IF:8.0) (Invited)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUAUY5QQFil1Xd4ilUlGp6PerDx4Q_VC3XdEW2EwSNaTKRdyLGyk6C_ag0E3z61zmkOW6gdsterOmsgiVISg-LR22pZ1wgSZvWq0-hOJuzXXt8R_TZ-zpAP3t7bJK6h1l_3up9M610idbmRMiYLRUl_gPD19FvrHHStp7lTcUV-0AZuel2E1I7R-mpTiqs-KsPoG4b2LuBGOO2MO8EQch6WkauqvDts5m_U8vGY%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Chiral Nanophotonics",
    "Note": ""
  },
  {
    "No": "[28]",
    "Year": "2025",
    "Category": "Integrated Photonics & Quantum",
    "Keywords": "Thin-Film Lithium Niobate, Mode Converter, Photon-pair Generation, Freeform Photonics",
    "Title": "Freeform Thin-Film Lithium Niobate Mode Converter for Photon-pair Generation",
    "Authors": "C. Kim†, M. Bae†, M. Choi, S. Lee, M. Lee, H. Jung, H. Chung*, H. Kwon*",
    "Journal": "Nanophotonics (2025) (IF:7.5)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUBdlAMQ8o0ntISnX16Fc0jh6nE1LlJy84q8fzgUtGronNsWJaXBq1_qkC8MHmb2UcYfhBw0IA5zeLR8K3lm1_QujovGt4UwGiuK91HEPPgpqs9B1lXtunwiQ3XRNR1Sbh9_AhvqghTfQOQVFaUUd0ySYsUdmD-eCe1oCVhIoj-waa8_ld4B7ldBSjbVhu1RFzb66rnGR3zMV5lFN1wLXRxzXhKWd56_gOvw%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Integrated Photonics",
    "Note": ""
  },
  {
    "No": "[27]",
    "Year": "2025",
    "Category": "AI & Computational Design",
    "Keywords": "Neural Operator, Fourier Neural Operator, Surrogate Solver, Metasurface, Wavefront Shaping",
    "Title": "Adjoint Method-based Fourier Neural Operator Surrogate Solver for Wavefront Shaping in Tunable Metasurfaces",
    "Authors": "C. Kang†, J. Seo†, I. Jang, H. Chung*",
    "Journal": "iScience (2025) (IF:6.107)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUAJIy21Znbf_W7XaWv62LidUWw73927ACfOKoRRn9nc8Xel-h0M9phQ9NN7Sl2rv9sUplx5r4OnjuFcRIipU8b7_WSG779g-6nj_cQQzfjO_UJhdBGUXT_65W11qYhMdvGUvzfvyObmzx5GimJHBOZsQlr02NJLZdgUqkejJNEInwFXou6AK1Dx%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Neural Operator / Metasurface",
    "Note": ""
  },
  {
    "No": "[27]",
    "Year": "2025",
    "Category": "AI & Computational Design",
    "Keywords": "Neural Operator, Fourier Neural Operator, Surrogate Solver, Metasurface, Wavefront Shaping",
    "Title": "Adjoint Method-based Fourier Neural Operator Surrogate Solver for Wavefront Shaping in Tunable Metasurfaces",
    "Authors": "C. Kang†, J. Seo†, I. Jang, H. Chung*",
    "Journal": "iScience (2025) (IF:6.107)",
    "Link": "",
    "Image": "https://lh3.googleusercontent.com/sitesv/AA5AbUAJIy21Znbf_W7XaWv62LidUWw73927ACfOKoRRn9nc8Xel-h0M9phQ9NN7Sl2rv9sUplx5r4OnjuFcRIipU8b7_WSG779g-6nj_cQQzfjO_UJhdBGUXT_65W11qYhMdvGUvzfvyObmzx5GimJHBOZsQlr02NJLZdgUqkejJNEInwFXou6AK1Dx%3Dw1280",
    "Source": "https://sites.google.com/view/eidl/publication",
    "OldCategory": "Neural Operator / Metasurface",
    "Note": ""
  }
];
